export const C = {
  bg: 'var(--color-bg)',
  surface: 'var(--color-surface)',
  surface2: 'var(--color-surface-2)',
  surface3: 'var(--color-surface-3)',
  amber: 'var(--color-amber)',
  amberDim: 'var(--color-amber-dim)',
  red: 'var(--color-red)',
  redDim: 'var(--color-red-dim)',
  green: 'var(--color-green)',
  greenDim: 'var(--color-green-dim)',
  blue: 'var(--color-blue)',
  gray: 'var(--color-gray)',
  text: 'var(--color-text)',
  textDim: 'var(--color-text-dim)',
  border: 'var(--color-border)',
  borderBright: 'var(--color-border-bright)',
  shadow: 'var(--shadow-card)',
};
